# Generated by Django 4.0.4 on 2023-05-14 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menusenddata',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.menus'),
        ),
        migrations.AddField(
            model_name='menusenddata',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.pet'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.pet'),
        ),
    ]
