# Generated by Django 4.0.4 on 2022-05-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='grams',
        ),
        migrations.AddField(
            model_name='puppy',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='points',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='sex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
