# Generated by Django 4.0.4 on 2022-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_remove_puppy_grams_puppy_age_puppy_points_puppy_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gramsdata',
            name='puntos',
            field=models.IntegerField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
