# Generated by Django 4.0.4 on 2023-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('años', 'años'), ('meses', 'meses')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Pescado', 'Pescado'), ('Huevo', 'Huevo'), ('Ninguna', 'Ninguna'), ('Pollo', 'Pollo'), ('Granos', 'Granos'), ('Res', 'Res'), ('Otro', 'Otro'), ('Cerdo', 'Cerdo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('sobrepeso', 'sobrepeso'), ('delgado', 'delgado'), ('peso_ideal', 'peso_ideal'), ('muy_delgado', 'muy_delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Ariticulaciones', 'Ariticulaciones'), ('Aliento', 'Aliento'), ('Diabetes', 'Diabetes'), ('Digestión', 'Digestión'), ('Piel', 'Piel'), ('Ansiedad', 'Ansiedad'), ('Ninguna', 'Ninguna'), ('Cancer', 'Cancer'), ('Hiperactividad', 'Hiperactividad'), ('Ganancia de peso', 'Ganancia de peso'), ('Urinario-renal', 'Urinario-renal'), ('Cardiovascular', 'Cardiovascular'), ('Control de peso', 'Control de peso')], default='Ninguna', max_length=255),
        ),
    ]
