# Generated by Django 4.0.4 on 2023-05-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_pet_age_type_alter_pet_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('meses', 'meses'), ('años', 'años')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Pescado', 'Pescado'), ('Pollo', 'Pollo'), ('Cerdo', 'Cerdo'), ('Res', 'Res'), ('Huevo', 'Huevo'), ('Granos', 'Granos'), ('Otro', 'Otro'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('muy_delgado', 'muy_delgado'), ('delgado', 'delgado'), ('sobrepeso', 'sobrepeso'), ('peso_ideal', 'peso_ideal')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Diabetes', 'Diabetes'), ('Ariticulaciones', 'Ariticulaciones'), ('Hiperactividad', 'Hiperactividad'), ('Urinario-renal', 'Urinario-renal'), ('Ansiedad', 'Ansiedad'), ('Piel', 'Piel'), ('Cancer', 'Cancer'), ('Cardiovascular', 'Cardiovascular'), ('Ninguna', 'Ninguna'), ('Aliento', 'Aliento'), ('Digestión', 'Digestión'), ('Control de peso', 'Control de peso'), ('Ganancia de peso', 'Ganancia de peso')], default='Ninguna', max_length=255),
        ),
    ]
