# Generated by Django 4.0.4 on 2022-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_gramsdata_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramsdata',
            name='puntos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
