# Generated by Django 4.0.4 on 2023-10-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_pet_age_type_alter_pet_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='price_per_100_grams',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Res', 'Res'), ('Otro', 'Otro'), ('Pollo', 'Pollo'), ('Ninguna', 'Ninguna'), ('Pescado', 'Pescado'), ('Granos', 'Granos'), ('Huevo', 'Huevo'), ('Cerdo', 'Cerdo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('peso_ideal', 'peso_ideal'), ('muy_delgado', 'muy_delgado'), ('sobrepeso', 'sobrepeso'), ('delgado', 'delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='reproductive_state',
            field=models.CharField(choices=[('castrado', 'castrado'), ('entero', 'entero')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Aliento', 'Aliento'), ('Diabetes', 'Diabetes'), ('Piel', 'Piel'), ('Hiperactividad', 'Hiperactividad'), ('Cardiovascular', 'Cardiovascular'), ('Ganancia de peso', 'Ganancia de peso'), ('Cancer', 'Cancer'), ('Ariticulaciones', 'Ariticulaciones'), ('Urinario-renal', 'Urinario-renal'), ('Ninguna', 'Ninguna'), ('Control de peso', 'Control de peso'), ('Digestión', 'Digestión'), ('Ansiedad', 'Ansiedad')], default='Ninguna', max_length=255),
        ),
    ]
