# Generated by Django 4.0.4 on 2022-06-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_gramsdata_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='activity_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='reproductive_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
