# Generated by Django 4.0.4 on 2024-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_menus_price_per_100_grams_alter_pet_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('años', 'años'), ('meses', 'meses')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Otro', 'Otro'), ('Pollo', 'Pollo'), ('Granos', 'Granos'), ('Res', 'Res'), ('Pescado', 'Pescado'), ('Huevo', 'Huevo'), ('Cerdo', 'Cerdo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('delgado', 'delgado'), ('muy_delgado', 'muy_delgado'), ('peso_ideal', 'peso_ideal'), ('sobrepeso', 'sobrepeso')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='reproductive_state',
            field=models.CharField(choices=[('entero', 'entero'), ('castrado', 'castrado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Control de peso', 'Control de peso'), ('Ninguna', 'Ninguna'), ('Diabetes', 'Diabetes'), ('Piel', 'Piel'), ('Digestión', 'Digestión'), ('Ansiedad', 'Ansiedad'), ('Cardiovascular', 'Cardiovascular'), ('Aliento', 'Aliento'), ('Hiperactividad', 'Hiperactividad'), ('Ariticulaciones', 'Ariticulaciones'), ('Ganancia de peso', 'Ganancia de peso'), ('Urinario-renal', 'Urinario-renal'), ('Cancer', 'Cancer')], default='Ninguna', max_length=255),
        ),
    ]
