# Generated by Django 4.0.4 on 2022-06-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_puppy_activity_level_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'sedentario'), (3, 'muy activo'), (2, 'actividad media')], default=1),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(1, 'muy delgado'), (5, 'obesidad'), (4, 'sobrepeso'), (3, 'peso ideal'), (2, 'delgado')], default=3),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(2, 'entero'), (1, 'castrado')], default=1),
        ),
    ]
