# Generated by Django 4.0.4 on 2022-06-09 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_alter_puppy_activity_level_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='breeds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('life_span', models.CharField(blank=True, max_length=255, null=True)),
                ('breed_group', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(2, 'actividad media'), (1, 'sedentario'), (3, 'muy activo')], default=1),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(4, 'sobrepeso'), (5, 'obesidad'), (3, 'peso ideal'), (2, 'delgado'), (1, 'muy delgado')], default=3),
        ),
    ]
