# Generated by Django 4.0.4 on 2022-06-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_breeds_alter_puppy_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'sedentario'), (3, 'muy activo'), (2, 'actividad media')], default=1),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(5, 'obesidad'), (3, 'peso ideal'), (2, 'delgado'), (1, 'muy delgado'), (4, 'sobrepeso')], default=3),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(1, 'castrado'), (2, 'entero')], default=1),
        ),
    ]
