# Generated by Django 4.0.4 on 2022-06-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_alter_puppy_activity_level_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(3, 'muy activo'), (1, 'sedentario'), (2, 'actividad media')], default=1),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(4, 'sobrepeso'), (3, 'peso ideal'), (2, 'delgado'), (5, 'obesidad'), (1, 'muy delgado')], default=3),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(2, 'entero'), (1, 'castrado')], default=1),
        ),
    ]
