# Generated by Django 4.0.4 on 2022-06-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_puppy_breed_alter_puppy_activity_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GramsData',
        ),
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(3, 'muy activo'), (2, 'actividad media'), (1, 'sedentario')], default=1),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(2, 'delgado'), (1, 'muy delgado'), (4, 'sobrepeso'), (3, 'peso ideal'), (5, 'obesidad')], default=3),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(1, 'castrado'), (2, 'entero')], default=1),
        ),
    ]
