# Generated by Django 4.0.4 on 2022-06-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0010_delete_gramsdata_alter_puppy_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(1, 'muy delgado'), (2, 'delgado'), (3, 'peso ideal'), (5, 'obesidad'), (4, 'sobrepeso')], default=3),
        ),
    ]
