# Generated by Django 4.0.4 on 2022-07-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_alter_puppy_body_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(2, 'actividad media'), (1, 'sedentario'), (3, 'muy activo')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(3, 'peso ideal'), (2, 'delgado'), (1, 'muy delgado'), (4, 'sobrepeso')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(1, 'castrado'), (2, 'entero')]),
        ),
    ]
