# Generated by Django 4.0.4 on 2022-07-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0012_alter_puppy_activity_level_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(3, 'muy activo'), (1, 'sedentario'), (2, 'actividad media')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(3, 'peso ideal'), (1, 'muy delgado'), (4, 'sobrepeso'), (2, 'delgado')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(2, 'entero'), (1, 'castrado')]),
        ),
    ]
