# Generated by Django 4.0.4 on 2022-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0013_alter_puppy_activity_level_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(1, 'muy delgado'), (4, 'sobrepeso'), (2, 'delgado'), (3, 'peso ideal')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(1, 'castrado'), (2, 'entero')]),
        ),
    ]
