# Generated by Django 4.0.4 on 2022-07-20 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0015_alter_puppy_activity_level_alter_puppy_body_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puppy',
            old_name='sex',
            new_name='grams',
        ),
        migrations.RenameField(
            model_name='puppy',
            old_name='size',
            new_name='grams_percent',
        ),
        migrations.AddField(
            model_name='puppy',
            name='allergies',
            field=models.IntegerField(choices=[(8, 'Pescado'), (6, 'Huevo'), (5, 'Granos'), (2, 'Pollo'), (4, 'Cerdo'), (3, 'Res'), (1, 'Ninguna'), (7, 'Otro')], default=1),
        ),
        migrations.AddField(
            model_name='puppy',
            name='is_barf_active',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='puppy',
            name='special_needs',
            field=models.IntegerField(choices=[(12, 'Diabetes'), (11, 'Cancer'), (4, 'Control de peso'), (7, 'Urinario-renal'), (13, 'Ganancia de peso'), (6, 'Ariticulaciones'), (9, 'Ansiedad'), (2, 'Digestión'), (5, 'Cardiovascular'), (3, 'Piel'), (1, 'Ninguna'), (10, 'Hiperactividad'), (8, 'Aliento')], default=1),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'sedentario'), (2, 'actividad media'), (3, 'muy activo')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(4, 'sobrepeso'), (2, 'delgado'), (3, 'peso ideal'), (1, 'muy delgado')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.IntegerField(choices=[(2, 'entero'), (1, 'castrado')]),
        ),
    ]
