# Generated by Django 4.0.4 on 2022-07-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0016_rename_sex_puppy_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.IntegerField(choices=[(3, 'muy activo'), (1, 'sedentario'), (2, 'actividad media')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Pescado', 'Pescado'), ('Otro', 'Otro'), ('Huevo', 'Huevo'), ('Cerdo', 'Cerdo'), ('Granos', 'Granos'), ('Res', 'Res'), ('Pollo', 'Pollo'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.IntegerField(choices=[(2, 'delgado'), (1, 'muy delgado'), (4, 'sobrepeso'), (3, 'peso ideal')]),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Hiperactividad', 'Hiperactividad'), ('Control de peso', 'Control de peso'), ('Ansiedad', 'Ansiedad'), ('Cancer', 'Cancer'), ('Ganancia de peso', 'Ganancia de peso'), ('Cardiovascular', 'Cardiovascular'), ('Aliento', 'Aliento'), ('Ninguna', 'Ninguna'), ('Ariticulaciones', 'Ariticulaciones'), ('Urinario-renal', 'Urinario-renal'), ('Digestión', 'Digestión'), ('Piel', 'Piel'), ('Diabetes', 'Diabetes')], default='Ninguna', max_length=255),
        ),
    ]
