# Generated by Django 4.0.4 on 2022-07-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0017_alter_puppy_activity_level_alter_puppy_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='activity_level',
            field=models.CharField(choices=[('bajo', 'sedentario'), ('medio', 'actividad media'), ('alto', 'muy activo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Huevo', 'Huevo'), ('Res', 'Res'), ('Cerdo', 'Cerdo'), ('Pescado', 'Pescado'), ('Pollo', 'Pollo'), ('Otro', 'Otro'), ('Ninguna', 'Ninguna'), ('Granos', 'Granos')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('peso ideal', 'peso ideal'), ('sobrepeso', 'sobrepeso'), ('delgado', 'delgado'), ('muy delgado', 'muy delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.CharField(choices=[('entero', 'entero'), ('castrado', 'castrado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Control de peso', 'Control de peso'), ('Piel', 'Piel'), ('Ansiedad', 'Ansiedad'), ('Urinario-renal', 'Urinario-renal'), ('Diabetes', 'Diabetes'), ('Cancer', 'Cancer'), ('Aliento', 'Aliento'), ('Cardiovascular', 'Cardiovascular'), ('Hiperactividad', 'Hiperactividad'), ('Digestión', 'Digestión'), ('Ariticulaciones', 'Ariticulaciones'), ('Ninguna', 'Ninguna'), ('Ganancia de peso', 'Ganancia de peso')], default='Ninguna', max_length=255),
        ),
    ]
