# Generated by Django 4.0.4 on 2022-07-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0020_alter_puppy_allergies_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Cerdo', 'Cerdo'), ('Granos', 'Granos'), ('Res', 'Res'), ('Pescado', 'Pescado'), ('Pollo', 'Pollo'), ('Otro', 'Otro'), ('Huevo', 'Huevo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('peso ideal', 'peso ideal'), ('muy delgado', 'muy delgado'), ('sobrepeso', 'sobrepeso'), ('delgado', 'delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Ganancia de peso', 'Ganancia de peso'), ('Control de peso', 'Control de peso'), ('Ninguna', 'Ninguna'), ('Cardiovascular', 'Cardiovascular'), ('Diabetes', 'Diabetes'), ('Urinario-renal', 'Urinario-renal'), ('Digestión', 'Digestión'), ('Aliento', 'Aliento'), ('Hiperactividad', 'Hiperactividad'), ('Ansiedad', 'Ansiedad'), ('Piel', 'Piel'), ('Cancer', 'Cancer'), ('Ariticulaciones', 'Ariticulaciones')], default='Ninguna', max_length=255),
        ),
    ]
