# Generated by Django 4.0.4 on 2022-11-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0024_alter_contactdetail_email_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Pescado', 'Pescado'), ('Granos', 'Granos'), ('Cerdo', 'Cerdo'), ('Pollo', 'Pollo'), ('Otro', 'Otro'), ('Ninguna', 'Ninguna'), ('Huevo', 'Huevo'), ('Res', 'Res')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('peso ideal', 'peso ideal'), ('delgado', 'delgado'), ('sobrepeso', 'sobrepeso'), ('muy delgado', 'muy delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.CharField(choices=[('entero', 'entero'), ('castrado', 'castrado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Cancer', 'Cancer'), ('Urinario-renal', 'Urinario-renal'), ('Ganancia de peso', 'Ganancia de peso'), ('Ansiedad', 'Ansiedad'), ('Digestión', 'Digestión'), ('Hiperactividad', 'Hiperactividad'), ('Ariticulaciones', 'Ariticulaciones'), ('Cardiovascular', 'Cardiovascular'), ('Aliento', 'Aliento'), ('Ninguna', 'Ninguna'), ('Control de peso', 'Control de peso'), ('Diabetes', 'Diabetes'), ('Piel', 'Piel')], default='Ninguna', max_length=255),
        ),
    ]
