# Generated by Django 4.0.4 on 2022-11-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0025_alter_puppy_allergies_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeds',
            name='breed_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Cerdo', 'Cerdo'), ('Granos', 'Granos'), ('Otro', 'Otro'), ('Huevo', 'Huevo'), ('Pescado', 'Pescado'), ('Res', 'Res'), ('Ninguna', 'Ninguna'), ('Pollo', 'Pollo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('sobrepeso', 'sobrepeso'), ('delgado', 'delgado'), ('muy delgado', 'muy delgado'), ('peso ideal', 'peso ideal')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.CharField(choices=[('castrado', 'castrado'), ('entero', 'entero')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Cardiovascular', 'Cardiovascular'), ('Aliento', 'Aliento'), ('Ariticulaciones', 'Ariticulaciones'), ('Cancer', 'Cancer'), ('Ganancia de peso', 'Ganancia de peso'), ('Ansiedad', 'Ansiedad'), ('Control de peso', 'Control de peso'), ('Diabetes', 'Diabetes'), ('Urinario-renal', 'Urinario-renal'), ('Hiperactividad', 'Hiperactividad'), ('Ninguna', 'Ninguna'), ('Digestión', 'Digestión'), ('Piel', 'Piel')], default='Ninguna', max_length=255),
        ),
    ]
