# Generated by Django 4.0.4 on 2022-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0026_breeds_breed_size_alter_puppy_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='age_type',
            field=models.CharField(choices=[('meses', 'meses'), ('años', 'años')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Huevo', 'Huevo'), ('Pollo', 'Pollo'), ('Ninguna', 'Ninguna'), ('Cerdo', 'Cerdo'), ('Res', 'Res'), ('Otro', 'Otro'), ('Granos', 'Granos'), ('Pescado', 'Pescado')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('delgado', 'delgado'), ('peso ideal', 'peso ideal'), ('sobrepeso', 'sobrepeso'), ('muy delgado', 'muy delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Digestión', 'Digestión'), ('Ansiedad', 'Ansiedad'), ('Ninguna', 'Ninguna'), ('Diabetes', 'Diabetes'), ('Urinario-renal', 'Urinario-renal'), ('Hiperactividad', 'Hiperactividad'), ('Cardiovascular', 'Cardiovascular'), ('Control de peso', 'Control de peso'), ('Ganancia de peso', 'Ganancia de peso'), ('Aliento', 'Aliento'), ('Ariticulaciones', 'Ariticulaciones'), ('Cancer', 'Cancer'), ('Piel', 'Piel')], default='Ninguna', max_length=255),
        ),
    ]
