# Generated by Django 4.0.4 on 2022-11-18 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0027_puppy_age_type_alter_puppy_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='default_name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients_description', models.TextField(blank=True, null=True)),
                ('nutrition_informatuion', models.TextField(blank=True, null=True)),
                ('percents', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='puppy',
            name='age_type',
            field=models.CharField(choices=[('años', 'años'), ('meses', 'meses')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Pollo', 'Pollo'), ('Res', 'Res'), ('Pescado', 'Pescado'), ('Otro', 'Otro'), ('Granos', 'Granos'), ('Cerdo', 'Cerdo'), ('Ninguna', 'Ninguna'), ('Huevo', 'Huevo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('sobrepeso', 'sobrepeso'), ('muy delgado', 'muy delgado'), ('peso ideal', 'peso ideal'), ('delgado', 'delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.CharField(choices=[('entero', 'entero'), ('castrado', 'castrado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Hiperactividad', 'Hiperactividad'), ('Cardiovascular', 'Cardiovascular'), ('Digestión', 'Digestión'), ('Control de peso', 'Control de peso'), ('Diabetes', 'Diabetes'), ('Cancer', 'Cancer'), ('Ariticulaciones', 'Ariticulaciones'), ('Urinario-renal', 'Urinario-renal'), ('Ganancia de peso', 'Ganancia de peso'), ('Aliento', 'Aliento'), ('Ansiedad', 'Ansiedad'), ('Ninguna', 'Ninguna'), ('Piel', 'Piel')], default='Ninguna', max_length=255),
        ),
    ]
