# Generated by Django 4.0.4 on 2022-11-20 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0029_rename_nutrition_informatuion_menus_nutrition_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dishes.menus'),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Granos', 'Granos'), ('Ninguna', 'Ninguna'), ('Otro', 'Otro'), ('Pollo', 'Pollo'), ('Res', 'Res'), ('Huevo', 'Huevo'), ('Pescado', 'Pescado'), ('Cerdo', 'Cerdo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('peso ideal', 'peso ideal'), ('sobrepeso', 'sobrepeso'), ('delgado', 'delgado'), ('muy delgado', 'muy delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Hiperactividad', 'Hiperactividad'), ('Cardiovascular', 'Cardiovascular'), ('Digestión', 'Digestión'), ('Ninguna', 'Ninguna'), ('Cancer', 'Cancer'), ('Piel', 'Piel'), ('Urinario-renal', 'Urinario-renal'), ('Aliento', 'Aliento'), ('Diabetes', 'Diabetes'), ('Control de peso', 'Control de peso'), ('Ansiedad', 'Ansiedad'), ('Ganancia de peso', 'Ganancia de peso'), ('Ariticulaciones', 'Ariticulaciones')], default='Ninguna', max_length=255),
        ),
    ]
