# Generated by Django 4.0.4 on 2023-02-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0030_puppy_menu_alter_puppy_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='age_type',
            field=models.CharField(choices=[('años', 'años'), ('meses', 'meses')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Granos', 'Granos'), ('Res', 'Res'), ('Pescado', 'Pescado'), ('Ninguna', 'Ninguna'), ('Pollo', 'Pollo'), ('Cerdo', 'Cerdo'), ('Huevo', 'Huevo'), ('Otro', 'Otro')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('delgado', 'delgado'), ('muy delgado', 'muy delgado'), ('peso ideal', 'peso ideal'), ('sobrepeso', 'sobrepeso')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.CharField(choices=[('entero', 'entero'), ('castrado', 'castrado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Control de peso', 'Control de peso'), ('Diabetes', 'Diabetes'), ('Ansiedad', 'Ansiedad'), ('Aliento', 'Aliento'), ('Hiperactividad', 'Hiperactividad'), ('Cancer', 'Cancer'), ('Ninguna', 'Ninguna'), ('Ganancia de peso', 'Ganancia de peso'), ('Piel', 'Piel'), ('Urinario-renal', 'Urinario-renal'), ('Cardiovascular', 'Cardiovascular'), ('Digestión', 'Digestión'), ('Ariticulaciones', 'Ariticulaciones')], default='Ninguna', max_length=255),
        ),
    ]
