# Generated by Django 4.0.4 on 2023-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0032_alter_puppy_allergies_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='allergies',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Huevo', 'Huevo'), ('Cerdo', 'Cerdo'), ('Res', 'Res'), ('Pollo', 'Pollo'), ('Otro', 'Otro'), ('Granos', 'Granos'), ('Pescado', 'Pescado')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='body_image',
            field=models.CharField(choices=[('peso ideal', 'peso ideal'), ('delgado', 'delgado'), ('muy delgado', 'muy delgado'), ('sobrepeso', 'sobrepeso')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='reproductive_state',
            field=models.CharField(choices=[('castrado', 'castrado'), ('entero', 'entero')], max_length=255),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='special_needs',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Aliento', 'Aliento'), ('Control de peso', 'Control de peso'), ('Ansiedad', 'Ansiedad'), ('Ariticulaciones', 'Ariticulaciones'), ('Digestión', 'Digestión'), ('Diabetes', 'Diabetes'), ('Cancer', 'Cancer'), ('Cardiovascular', 'Cardiovascular'), ('Piel', 'Piel'), ('Hiperactividad', 'Hiperactividad'), ('Urinario-renal', 'Urinario-renal'), ('Ganancia de peso', 'Ganancia de peso')], default='Ninguna', max_length=255),
        ),
    ]
