# Generated by Django 4.0.4 on 2023-04-09 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0033_alter_puppy_allergies_alter_puppy_body_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('age_type', models.CharField(choices=[('años', 'años'), ('meses', 'meses')], default='años', max_length=255)),
                ('body_image', models.CharField(choices=[('sobrepeso', 'sobrepeso'), ('peso_ideal', 'peso_ideal'), ('muy_delgado', 'muy_delgado'), ('delgado', 'delgado')], max_length=255)),
                ('reproductive_state', models.CharField(choices=[('entero', 'entero'), ('castrado', 'castrado')], max_length=255)),
                ('activity_level', models.CharField(max_length=255)),
                ('allergies', models.CharField(choices=[('Granos', 'Granos'), ('Cerdo', 'Cerdo'), ('Pescado', 'Pescado'), ('Otro', 'Otro'), ('Pollo', 'Pollo'), ('Huevo', 'Huevo'), ('Ninguna', 'Ninguna'), ('Res', 'Res')], default='Ninguna', max_length=255)),
                ('special_needs', models.CharField(choices=[('Hiperactividad', 'Hiperactividad'), ('Aliento', 'Aliento'), ('Urinario-renal', 'Urinario-renal'), ('Piel', 'Piel'), ('Control de peso', 'Control de peso'), ('Diabetes', 'Diabetes'), ('Ganancia de peso', 'Ganancia de peso'), ('Ansiedad', 'Ansiedad'), ('Cancer', 'Cancer'), ('Cardiovascular', 'Cardiovascular'), ('Digestión', 'Digestión'), ('Ninguna', 'Ninguna'), ('Ariticulaciones', 'Ariticulaciones')], default='Ninguna', max_length=255)),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('grams', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('grams_percent', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('points', models.IntegerField(default=0)),
                ('is_barf_active', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dishes.menus')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.pet'),
        ),
        migrations.DeleteModel(
            name='Puppy',
        ),
    ]
