# Generated by Django 4.0.4 on 2023-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0034_pet_alter_contactdetail_pet_delete_puppy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('meses', 'meses'), ('años', 'años')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Pollo', 'Pollo'), ('Pescado', 'Pescado'), ('Granos', 'Granos'), ('Res', 'Res'), ('Otro', 'Otro'), ('Cerdo', 'Cerdo'), ('Ninguna', 'Ninguna'), ('Huevo', 'Huevo')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('muy_delgado', 'muy_delgado'), ('peso_ideal', 'peso_ideal'), ('delgado', 'delgado'), ('sobrepeso', 'sobrepeso')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='reproductive_state',
            field=models.CharField(choices=[('castrado', 'castrado'), ('entero', 'entero')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Cancer', 'Cancer'), ('Hiperactividad', 'Hiperactividad'), ('Diabetes', 'Diabetes'), ('Ariticulaciones', 'Ariticulaciones'), ('Aliento', 'Aliento'), ('Ganancia de peso', 'Ganancia de peso'), ('Urinario-renal', 'Urinario-renal'), ('Ninguna', 'Ninguna'), ('Piel', 'Piel'), ('Digestión', 'Digestión'), ('Ansiedad', 'Ansiedad'), ('Control de peso', 'Control de peso'), ('Cardiovascular', 'Cardiovascular')], default='Ninguna', max_length=255),
        ),
    ]
