# Generated by Django 4.0.4 on 2023-04-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0035_alter_pet_age_type_alter_pet_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('años', 'años'), ('meses', 'meses')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Granos', 'Granos'), ('Cerdo', 'Cerdo'), ('Otro', 'Otro'), ('Huevo', 'Huevo'), ('Ninguna', 'Ninguna'), ('Pescado', 'Pescado'), ('Pollo', 'Pollo'), ('Res', 'Res')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('muy_delgado', 'muy_delgado'), ('peso_ideal', 'peso_ideal'), ('sobrepeso', 'sobrepeso'), ('delgado', 'delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='reproductive_state',
            field=models.CharField(choices=[('entero', 'entero'), ('castrado', 'castrado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Ariticulaciones', 'Ariticulaciones'), ('Digestión', 'Digestión'), ('Urinario-renal', 'Urinario-renal'), ('Ganancia de peso', 'Ganancia de peso'), ('Ansiedad', 'Ansiedad'), ('Ninguna', 'Ninguna'), ('Piel', 'Piel'), ('Cancer', 'Cancer'), ('Control de peso', 'Control de peso'), ('Cardiovascular', 'Cardiovascular'), ('Aliento', 'Aliento'), ('Hiperactividad', 'Hiperactividad'), ('Diabetes', 'Diabetes')], default='Ninguna', max_length=255),
        ),
        migrations.CreateModel(
            name='MenuSendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_interval', models.PositiveIntegerField(default=0)),
                ('last_sent_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.menus')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.pet')),
            ],
        ),
    ]
