# Generated by Django 4.0.4 on 2023-04-10 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0036_alter_pet_age_type_alter_pet_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusenddata',
            name='id',
        ),
        migrations.AddField(
            model_name='menusenddata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('meses', 'meses'), ('años', 'años')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Pescado', 'Pescado'), ('Huevo', 'Huevo'), ('Granos', 'Granos'), ('Pollo', 'Pollo'), ('Cerdo', 'Cerdo'), ('Res', 'Res'), ('Otro', 'Otro'), ('Ninguna', 'Ninguna')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('delgado', 'delgado'), ('sobrepeso', 'sobrepeso'), ('muy_delgado', 'muy_delgado'), ('peso_ideal', 'peso_ideal')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Urinario-renal', 'Urinario-renal'), ('Control de peso', 'Control de peso'), ('Hiperactividad', 'Hiperactividad'), ('Diabetes', 'Diabetes'), ('Ansiedad', 'Ansiedad'), ('Digestión', 'Digestión'), ('Piel', 'Piel'), ('Cancer', 'Cancer'), ('Cardiovascular', 'Cardiovascular'), ('Ariticulaciones', 'Ariticulaciones'), ('Ganancia de peso', 'Ganancia de peso'), ('Ninguna', 'Ninguna'), ('Aliento', 'Aliento')], default='Ninguna', max_length=255),
        ),
    ]
