# Generated by Django 4.0.4 on 2023-04-10 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0037_alter_menusenddata_id_alter_pet_age_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusenddata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menusenddata',
            name='last_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('años', 'años'), ('meses', 'meses')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Huevo', 'Huevo'), ('Otro', 'Otro'), ('Ninguna', 'Ninguna'), ('Pescado', 'Pescado'), ('Pollo', 'Pollo'), ('Cerdo', 'Cerdo'), ('Res', 'Res'), ('Granos', 'Granos')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('peso_ideal', 'peso_ideal'), ('delgado', 'delgado'), ('sobrepeso', 'sobrepeso'), ('muy_delgado', 'muy_delgado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='reproductive_state',
            field=models.CharField(choices=[('castrado', 'castrado'), ('entero', 'entero')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Piel', 'Piel'), ('Ansiedad', 'Ansiedad'), ('Ariticulaciones', 'Ariticulaciones'), ('Urinario-renal', 'Urinario-renal'), ('Control de peso', 'Control de peso'), ('Cardiovascular', 'Cardiovascular'), ('Ninguna', 'Ninguna'), ('Digestión', 'Digestión'), ('Hiperactividad', 'Hiperactividad'), ('Cancer', 'Cancer'), ('Ganancia de peso', 'Ganancia de peso'), ('Aliento', 'Aliento'), ('Diabetes', 'Diabetes')], default='Ninguna', max_length=255),
        ),
    ]
