# Generated by Django 4.0.4 on 2023-04-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0038_alter_menusenddata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('meses', 'meses'), ('años', 'años')], default='años', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(choices=[('Pollo', 'Pollo'), ('Granos', 'Granos'), ('Ninguna', 'Ninguna'), ('Pescado', 'Pescado'), ('Huevo', 'Huevo'), ('Cerdo', 'Cerdo'), ('Otro', 'Otro'), ('Res', 'Res')], default='Ninguna', max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='body_image',
            field=models.CharField(choices=[('muy_delgado', 'muy_delgado'), ('peso_ideal', 'peso_ideal'), ('delgado', 'delgado'), ('sobrepeso', 'sobrepeso')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(choices=[('Cancer', 'Cancer'), ('Ansiedad', 'Ansiedad'), ('Ninguna', 'Ninguna'), ('Aliento', 'Aliento'), ('Diabetes', 'Diabetes'), ('Ariticulaciones', 'Ariticulaciones'), ('Hiperactividad', 'Hiperactividad'), ('Cardiovascular', 'Cardiovascular'), ('Piel', 'Piel'), ('Digestión', 'Digestión'), ('Urinario-renal', 'Urinario-renal'), ('Control de peso', 'Control de peso'), ('Ganancia de peso', 'Ganancia de peso')], default='Ninguna', max_length=255),
        ),
    ]
