# Generated by Django 4.0.4 on 2023-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('from_address', models.EmailField(max_length=254)),
                ('to_address', models.EmailField(max_length=254)),
                ('cc_address', models.EmailField(blank=True, max_length=254)),
                ('bcc_address', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
