# Generated by Django 4.0.4 on 2023-05-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='addresses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
